name = "lil botania pack"
author = "cplir-c"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b1f226e069bce11b0b2f1f5126c7b2c5cad08c373b64403c588a7b2be772fcb7"

[versions]
minecraft = "1.19.2"
quilt = "0.18.9"
